### ISSUE TITLE
Is there a way to pass userdata?

### ISSUE THREAD

**Issue by TonyMilton** [crow-misia/go-libsoundio#3]
Is there a way to pass userdata so that it's available to from within SetWriteCallback? It appears libsoundio has a userdata property on SoundIoOutStream

http://libsound.io/doc-2.0.0/structSoundIoOutStream.html#a14549e062b980bf32254718403c55ca2

I'm looking to pass an array of bytes of audio data to then pass to the buffer to write within SetWriteCallback.

**Comment by crow-misia** [comment]
@TonyMilton 
userdata itself cannot be used, as it is used internally to proces callback.
However, variables outside scope of your callback can be used, so there should be no need to use userdata.

For example.
```
	counter := 1

	outStream.SetWriteCallback(func(stream *soundio.OutStream, frameCountMix int, frameCountMax int) {
		counter++
		log.Println(counter)
```
