### ISSUE TITLE
ChannelAreas.Buffer is making wrong assumptions

### ISSUE THREAD

**Issue by Seb-C** [crow-misia/go-libsoundio#6]
The `ChannelAreas.Buffer` method is assuming that the step is always equal to `channelCount * sampleSize`, and provides a buffer that is sliced based on this rule.

However, this is not always true, it seems to depend on the backend.

Below is what I observed, using the following example:
- Stereo layout (2 channels)
- Using a float32 format (4 bytes per sample and channel)
- To make things readable, I will name samples like `CxSy`, where `x` is the channel index and `y` is the sample index

### On my PC (PulseAudio)

All the areas points to the same buffer, where each channel samples are alternating

The layout of the memory is like this: `[C0S0, C1S0, C0S1, C1S1, C0S2, C1S2, ...]`.

In this case, the step provided by each area will be 8 bytes (`2 channels * 4 bytes`), as assumed by this package.

### On a Steam Deck (Jack by default)

Each of the areas have an independent, non-shared buffer.

The layout in memory is like this:
- Buffer of area 0: `[C0S0, C0S1, C0S2, ...]`
- Buffer of area 1: `[C1S0, C1S1, C1S2, ...]`

In this case, the step provided by each area will be 4 bytes, and `ChannelAreas.Buffer` returns a byte slice with a length of `2`, which is wrong and not usable since it is not possible to write a float32 into 2 bytes.

### What to do?

I am willing to make a PR for this, but I am not sure what design would be the best since it cannot be fixed without breaking backward-compatibility.

- Provide a slice which is always have the same size than the step. This means that we assume that the developer should not touch the trailing bytes (might be risky and unexpected)
- Have a mechanism to determine the byte length of each format, and have this method return a slice that starts at the right offset (based on the step) and is limited to a size determined by the format (might be a bit overkill)
- Remove `ChannelAreas.Buffer` completely and let the developers stick to the way originally intended by libsoundio.

How would you prefer to proceed?

**Comment by Seb-C** [comment]
I figured-out later that the Jack driver is also causing lots of issues on Steam Deck (basically it does not support anything but one format/layout/rate). Maybe it depends on the backend.

**Comment by crow-misia** [comment]
@Seb-C 

The buffer size was calculated from steps, but when Jack used, it set to bytesPerSample, and when PulseAudio used, it set to bytesPerFrame.

When using Jack, bytesPerSample was divided by the channel count, resulting in a smaller size.

The buffer size is now returned as bytesPerSample instead of being calculated from steps.

I cannot test because I have no Jack environment.

Please check.

**Comment by Seb-C** [comment]
@crow-misia Thank you! I tested again and now it works correctly.
